<?php

$form->get('text')->setAttributes([
    'class'=>'uk-input uk-width-1-2',
    'id'=>'commentaire'
]);

$form->get('submit')->setAttributes([
    'class'=>'uk-button uk-button-default'
]);

$form->prepare();
?>

<div class="uk-grid-match uk-grid-small" uk-grid>
    <div class="uk-text-justify uk-grid-item-match">
        <div>
            <h1 class="uk-heading-divider"><?= $article->getTitle() ?>
                <?php
                    if($this->identity()->getRole() == 1 || $this->identity()->getRole() == $creatorOfArticle->getId()) {
                        echo "
                        <span class='uk-align-right'>
                            <a class='uk-button uk-button-default' href='".$this->url('edit.articles', array('id'=>$article->getId()))."'>Modifier</a>
                        </span>";
                    }
                ?>
            </h1>

            <?= $article->getText() ?>
        </div>
    </div>
</div>


<div class="uk-text-right">
    Crée par <?= $creatorOfArticle->getFullName() ?>
    le <?= $article->getDate_created() ?>
</div>
<h3 class="uk-heading-divider">Commentaires</h3>
<div class="uk-grid-match uk-grid-small">
    <div class="uk-text-justify uk-grid-item-match">
        <?= $this->form()->openTag($form); ?>
                <?= $this->formElement($form->get('csrf')); ?>

                <div class="uk-margin">
                    <?= $this->formElement($form->get('text')); ?>
                    <?= $this->formElementErrors($form->get('text')); ?>
                </div>

                <?= $this->formElement($form->get('submit')); ?>
        <?= $this->form()->closeTag(); ?>
    </div>
</div>

<?php foreach ($commentaires as $commentaire) : ?>
<hr>
<article class="uk-comment uk-comment-primary">
    <header class="uk-comment-header uk-grid-medium uk-flex-middle" uk-grid>
        <div class="uk-width-expand">
            <h4 class="uk-comment-title uk-margin-remove"><a class="uk-link-reset" href="#"><?= $this->escapeHtml($commentaire->getUser()->getFullName()) ?></a></h4>
            <ul class="uk-comment-meta uk-subnav uk-subnav-divider uk-margin-remove-top">
                <li><a href="#"><?= $this->escapeHtml($commentaire->getDate_created()) ?></a></li>
            </ul>
        </div>
    </header>
    <div class="uk-comment-body">
        <p><?= $commentaire->getText() ?></p>
    </div>
</article>
<?php endforeach; ?>
