<?= $this->doctype() ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?= $this->headTitle('')->setSeparator(' - ')->setAutoEscape(false) ?>

        <?= $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?= $this->headLink(['rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'])
            ->prependStylesheet($this->basePath('css/jquery-ui.structure.min.css'))
            ->prependStylesheet($this->basePath('css/jquery-ui.min.css'))
            ->prependStylesheet($this->basePath('css/style.css'))
            ->prependStylesheet($this->basePath('css/uikit.min.css'))
            ->prependStylesheet($this->basePath('css/uikit-rtl.min.css'))
        ?>

        <!-- Scripts -->
        <?= $this->headScript()
        ->prependFile($this->basePath('js/jquery-ui.min.js'))
        ->prependFile($this->basePath('js/editor.js'))
        ->prependFile($this->basePath('js/tinymce/tinymce.min.js'))
        ->prependFile($this->basePath('js/uikit-icons.min.js'))
        ->prependFile($this->basePath('js/uikit.min.js'))
        ->prependFile($this->basePath('js/jquery-3.1.0.min.js'))
        ?>
        <script type="text/javascript">
            $(function () {
                $.ajax({
                    url: "<?= $this->url("listJson.articles") ?>",
                    type: "GET",
                    dataType: "json",
                    success: function(data) {
                        $("#search_article").autocomplete({
                            minLength: 3,
                            autoFocus: true,
                            source : data,
                            select: function(e, ui) {
                                var url = "<?= $this->url("redirectlist.articles")?>"+"?title="+$("#search_article").val();
                                window.location.href = url;
                            },
                        });
                    }
                });

                $("#btn_search_article").on("click", function(){
                    var url = "<?= $this->url("redirectlist.articles")?>"+"?title="+$("#search_article").val();
                    window.location.href = url;
                });
            });
        </script>
    </head>
    <body>
        <?php $user = $this->identity(); ?>
        <div class="uk-offcanvas-content">
            <div id="offcanvas-reveal" uk-offcanvas="mode: reveal">
                <div class="uk-offcanvas-bar">
                    <button class="uk-offcanvas-close" type="button" uk-close></button>
                    <a class="uk-navbar-item" href="<?= $this->url('home') ?>">Accueil</a>
                    <?php if($user != null && $user->getRole()) : ?>
                        <a class="uk-navbar-item" href="<?= $this->url('add.articles') ?>">Ajouter un article</a>
                        <a class="uk-navbar-item" href="<?= $this->url('list.users') ?>">Liste des utilisateurs</a>
                    <?php endif; ?>
                    <?php if($user) : ?>
                        <a class="uk-navbar-item" href="<?= $this->url('deconnexion') ?>">Se déconnecter</a>
                    <?php else : ?>
                        <a class="uk-navbar-item" href="<?= $this->url('connexion') ?>">Se connecter</a>
                    <?php endif; ?>
                </div>
            </div>
        </div>
        <nav class="uk-navbar-container" uk-navbar>
            <div class="uk-navbar-left">
                <ul class="uk-navbar-nav">
                    <li><a class="uk-navbar-item uk-logo" href="#"><img src="<?= $this->basePath('img/logo.png') ?>" alt="WikiTema"></a></li>
                    <li class="uk-active uk-visible@l"><a href="<?= $this->url('home') ?>">Accueil</a></li>
                    <?php if($user != null && $user->getRole()) : ?>
                        <li><a class="uk-navbar-item uk-visible@l" href="<?= $this->url('add.articles') ?>">Ajouter un article</a></li>
                        <li><a class="uk-navbar-item uk-visible@l" href="<?= $this->url('list.users') ?>">Liste des utilisateurs</a></li>
                    <?php endif; ?>
                </ul>
            </div>
            <div class="uk-navbar-right">
                <ul class="uk-navbar-nav">
                    <?php if($user) : ?>
                        <div class="uk-navbar-item">
                            <form class="uk-search uk-search-default">
                                <a id="btn_search_article" class="uk-search-icon-flip" uk-search-icon></a>
                                <input id="search_article" class="uk-search-input" type="search" placeholder="Recherche...">
                            </form>
                        </div>
                        <li><a class="uk-navbar-item uk-visible@l" href="<?= $this->url('deconnexion') ?>">Se déconnecter</a></li>
                    <?php else : ?>
                        <li><a class="uk-navbar-item uk-visible@l" href="<?= $this->url('connexion') ?>">Se connecter</a></li>
                    <?php endif; ?>
                    <li><a class="uk-navbar-toggle uk-hidden@l" uk-navbar-toggle-icon href="" uk-toggle="target: #offcanvas-reveal"></a></li>
                </ul>
            </div>
        </nav>
        <div class="uk-section uk-section-default">
            <div class="uk-container uk-position-relative">
                <div data-editable data-name="main-content">
                    <?= $this->content ?>
                </div>
            </div>
        </div>
        <footer class="uk-modal-footer uk-background-muted">
            <div class="uk-container">
                <p>&copy; <?= date('Y') ?> by Axel Bolo, Bastien Koson, Alexandre Moreau & Vissarut Ly.</p>
                <p><a class="uk-icon-button" href="https://github.com/Lyrut/wikitema" target="_blank" uk-icon="icon: github"></a></p>
            </div>
        </footer>
        <?= $this->inlineScript() ?>
    </body>
</html>
