<?= $this->doctype() ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?= $this->headTitle('')->setSeparator(' - ')->setAutoEscape(false) ?>

        <?= $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?= $this->headLink(['rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'])
            ->prependStylesheet($this->basePath('css/style.css'))
            ->prependStylesheet($this->basePath('css/uikit-rtl.min.css'))
            ->prependStylesheet($this->basePath('css/uikit.min.css'))
        ?>

        <!-- Scripts -->
        <?= $this->headScript()
        ->prependFile($this->basePath('js/tinymce/tinymce.min.js'))
        ->prependFile($this->basePath('js/tinymce/jquery.tinymce.min.js'))
        ->prependFile($this->basePath('js/uikit-icons.min.js'))
        ->prependFile($this->basePath('js/uikit.min.js'))
        ->prependFile($this->basePath('js/jquery-3.1.0.min.js'))
        ?>
        <script>
            tinymce.init({
                selector: '#create_article',
                theme: 'modern',
                plugins: [
                    'advlist autolink lists link image charmap print preview hr anchor pagebreak',
                    'searchreplace wordcount visualblocks visualchars code fullscreen',
                    'insertdatetime media nonbreaking save table contextmenu directionality',
                    'emoticons template paste textcolor colorpicker textpattern imagetools codesample toc help'
                ],
                toolbar1: 'undo redo | insert | styleselect | bold italic | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | link image',
                toolbar2: 'print preview media | forecolor backcolor emoticons | codesample help'
            });
        </script>
    </head>
    <body>
        <nav class="uk-navbar-container" uk-navbar>
            <div class="uk-navbar-left">
                <ul class="uk-navbar-nav">
                    <li><a class="uk-navbar-item uk-logo" href="#">Wikitema</a></li>
                    <li class="uk-active"><a href="<?= $this->url('home') ?>">Accueil</a></li>
                </ul>
            </div>
            <div class="uk-navbar-right">
                <ul class="uk-navbar-nav">
                    <div class="uk-navbar-item">
                        <form class="uk-search uk-search-default">
                            <a href="" class="uk-search-icon-flip" uk-search-icon></a>
                            <input class="uk-search-input" type="search" placeholder="Recherche...">
                        </form>
                    </div>
                    <li><a class="uk-navbar-item" href="<?= $this->url('connexion') ?>">Se connecter</a></li>
                </ul>
            </div>
        </nav>
        <hr>
        <section class="uk-section">
            <div class="uk-container">
                <?= $this->content ?>

                <!--form method="post">
                    <textarea id="create_article"><?= $this->content ?></textarea>
                </form-->
            </div>
        </section>
        <footer class="uk-modal-footer">
            <div class="uk-container">
                <div class="content">
                    <p>&copy; <?= date('Y') ?> by Axel Bolo, Bastien Koson, Alexandre Moreau & Vissarut Ly.</p>
                    <p><a class="uk-icon-button" href="https://github.com/Lyrut/wikitema" target="_blank" uk-icon="icon: github"></a></p>
                </div>
            </div>
        </footer>
        <?= $this->inlineScript() ?>
    </body>
</html>
