<?php

$form->get('email')->setAttributes([
    'class'=>'uk-input', 
    'placeholder'=>'Pseudo ou Mail',
    'required' => true,
    'autofocus' => true
    ]);

$form->get('password')->setAttributes([
    'class'=>'uk-input', 
    'placeholder'=>'Mot de passe',
    'required' => true,
    ]);
?>

<form method="post">
    <?= $this->formElement($form->get('csrf')); ?>
	<div class="uk-align-left">
        <div class="uk-inline">
            <span class="uk-form-icon" uk-icon="icon: user"></span>
			<?= $this->formElement($form->get('email')); ?>
        </div>
		
		<div class="uk-margin">
        <div class="uk-inline">
            <span class="uk-form-icon uk-form-icon-flip" uk-icon="icon: lock"></span>
			<?= $this->formElement($form->get('password')); ?>
        </div>
    </div>
    </div>
		<div class="uk-margin">
		<div uk-form-custom="target: true">
			<input type="file">
        </div>
        <button class="uk-button uk-button-default">Mot de passe oublié ?</button>
	</div>
	<div class="uk-align-left">
		<div uk-form-custom="target: true">
			<input type="file">
        </div>
        <input type="submit" class="uk-button uk-button-default" value="Valider">
	</div>
</form>

<div class="uk-align-right">
	Pas de compte ?
	<div uk-form-custom="target: true">
		<input type="file">
	</div>
	<a href="<?= $this->url('add.users'); ?>" class="uk-button uk-button-default">Inscription</a>
</div>
