<?php

$form->get('email')->setAttributes([
    'class'=>'uk-input',
    'placeholder'=>'Mail',
    'required' => true,
    'autofocus' => true
    ]);

$form->get('password')->setAttributes([
    'class'=>'uk-input',
    'placeholder'=>'Mot de passe',
    'required' => true,
    ]);
?>
<div class="uk-grid uk-grid-small uk-text-center">
  <div class="uk-width-1-2">
      <div>
          <div class="uk-tile uk-tile-muted uk-padding-remove">
              <p class="uk-h4">Se connecter</p>
          </div>
          <form method="post">
            <?= $this->formElement($form->get('csrf')); ?>
            <div class="uk-align-center">
                <div class="uk-inline uk-width-1-3@s">
                    <span class="uk-form-icon" uk-icon="icon: user"></span>
                    <?= $this->formElement($form->get('email')); ?>
                </div>
                <div class="uk-inline uk-width-1-3@s">
                    <span class="uk-form-icon" uk-icon="icon: lock"></span>
                    <?= $this->formElement($form->get('password')); ?>
                </div>
            </div>

            <div class="uk-align-center">
                <div uk-form-custom="target: true">
                    <input type="file">
                </div>
                <input type="submit" class="uk-button uk-button-default uk-width-2-5 uk-width-1-3@s" value="Valider">

                <div uk-form-custom="target: true">
          			<input type="file">
                </div>
                <input type="button" class="uk-button uk-button-default uk-width-2-5 uk-width-1-3@s" value="Mot de passe oublié ?">

            </div>
          </form>
      </div>
  </div>

  <div class="uk-width-1-2">
      	Pas de compte ?
      	<div uk-form-custom="target: true">
      		<input type="file">
      	</div>
      	<a href="<?= $this->url('add.users'); ?>" class="uk-button uk-button-default">Inscription</a>
  </div>
</div>
