<form>

    <div class="uk-align-left">
        <div class="uk-inline">
            <span class="uk-form-icon" uk-icon="icon: user"></span>
            <input class="uk-input" type="text" placeholder="Pseudo ou Mail">
        </div>
    </div>

    <div class="uk-margin">
        <div class="uk-inline">
            <span class="uk-form-icon uk-form-icon-flip" uk-icon="icon: lock"></span>
            <input class="uk-input" type="text" placeholder="Mot de passe">
        </div>
    </div>
	<div class="uk-margin">
		<div uk-form-custom="target: true">
			<input type="file">
        </div>
        <button class="uk-button uk-button-default">Mot de passe oublié ?</button>
	</div>
	<div class="uk-align-left">
		<div uk-form-custom="target: true">
			<input type="file">
        </div>
        <button class="uk-button uk-button-default">Valider</button>
	</div>
</form>