<?php

$form->get('email')->setAttributes([
    'class'=>'uk-input', 
    'placeholder'=>'Mail'
    ]);

$form->get('full_name')->setAttributes([
    'class'=>'uk-input', 
    'placeholder'=>'Nom et Prénom'
    ]);

$form->get('pseudo')->setAttributes([
    'class'=>'uk-input', 
    'placeholder'=>'Pseudo'
    ]);

$form->get('password')->setAttributes([
    'class'=>'uk-input'
    ]);

$form->get('confirm_password')->setAttributes([
    'class'=>'uk-input'
    ]);

$form->get('select_role')->setAttributes([
    'class'=>'form-control'
    ]);

$form->get('submit')->setAttributes(['class'=>'uk-button']);

$form->prepare();
?>

<form method="post" class="uk-form-stacked">
<?= $this->formElement($form->get('csrf')); ?>
	<div class="uk-align-center">
        <div class="uk-inline">
            <span class="uk-form-icon" uk-icon="icon: user"></span>
			<?= $this->formElement($form->get('email')); ?>
			<?= $this->formElementErrors($form->get('email')); ?>
        </div>
		<div class="uk-inline">
            <span class="uk-form-icon" uk-icon="icon: user"></span>
			<?= $this->formElement($form->get('full_name')); ?>
			<?= $this->formElementErrors($form->get('full_name')); ?> 
        </div>
		<div class="uk-inline">
            <span class="uk-form-icon" uk-icon="icon: user"></span>
			<?= $this->formElement($form->get('pseudo')); ?>
			<?= $this->formElementErrors($form->get('pseudo')); ?> 
        </div>
		<div class="uk-inline">
            <span class="uk-form-icon uk-form-icon-flip" uk-icon="icon: lock" placeholder="Mot de passe"></span>
			<?= $this->formElement($form->get('password')); ?>
			<?= $this->formElementErrors($form->get('password')); ?> 
        </div>
		<div class="uk-inline" value="mdp">
            <span class="uk-form-icon uk-form-icon-flip" uk-icon="icon: lock"></span>
			<?= $this->formElement($form->get('confirm_password')); ?>
			<?= $this->formElementErrors($form->get('confirm_password')); ?> 
        </div>
        <div class="form-group">
            <?= $this->formLabel($form->get('select_role')); ?>
            <?= $this->formElement($form->get('select_role')); ?>
            <?= $this->formElementErrors($form->get('select_role')); ?>                  
        </div>
        <?= $this->formElement($form->get('submit')); ?>
        <?= $this->form()->closeTag(); ?>
    </div>    
</div>  
