<?php

$form->get('email')->setAttributes([
    'class'=>'uk-input',
    'placeholder'=>'Mail'
    ]);

$form->get('full_name')->setAttributes([
    'class'=>'uk-input',
    'placeholder'=>'Nom et Prénom'
    ]);

$form->get('pseudo')->setAttributes([
    'class'=>'uk-input',
    'placeholder'=>'Pseudo'
    ]);

$form->get('password')->setAttributes([
    'class'=>'uk-input',
	'placeholder'=>'Mot de passe',
    ]);

$form->get('confirm_password')->setAttributes([
    'class'=>'uk-input',
	'placeholder'=>'Confirmation mot de passe',
    ]);

$form->get('select_role')->setAttributes([
    'class'=>'uk-select'
    ]);

$form->get('submit')->setAttributes(['class'=>'uk-button']);

$form->prepare();
?>
<div class="uk-grid uk-grid-small" uk-grid>
    <div class="uk-width-3-3@m uk-text-center">
        <form method="post">
            <fieldset class="uk-fieldset">
                <?php if (!$user) : ?>
                    <legend class="uk-legend">Inscription</legend>
                <?php else : ?>
                    <legend class="uk-legend">Ajout d'un utilisateur</legend>
                <?php endif; ?>
                <?= $this->formElement($form->get('csrf')); ?>
                <div class="uk-margin">
                    <div class="uk-inline">
                        <span class="uk-form-icon" uk-icon="icon: mail"></span>
                        <?= $this->formElement($form->get('email')); ?>
                    </div>
                        <?=
                            $this->formElementErrors()
                            ->setMessageOpenFormat('<div class="uk-alert-danger uk-text-center" uk-alert><a class="uk-alert-close uk-text-right" uk-close></a><p>')
                            ->setMessageSeparatorString('</p></div><div class="uk-alert-danger uk-text-center" uk-alert><a class="uk-alert-close uk-text-right" uk-close></a><p>')
                            ->setMessageCloseString('</p></div>')
                            ->render($form->get('email'));
                        ?>
                </div>
            	<div class="uk-margin">
                    <div class="uk-inline">
                        <span class="uk-form-icon" uk-icon="icon: user"></span>
            			<?= $this->formElement($form->get('full_name')); ?>
                    </div>
                        <?=
                            $this->formElementErrors()
                            ->setMessageOpenFormat('<div class="uk-alert-danger uk-text-center" uk-alert><a class="uk-alert-close uk-text-right" uk-close></a><p>')
                            ->setMessageSeparatorString('</p></div><div class="uk-alert-danger uk-text-center" uk-alert><a class="uk-alert-close uk-text-right" uk-close></a><p>')
                            ->setMessageCloseString('</p></div>')
                            ->render($form->get('full_name'));
                        ?>
                </div>
            	<div class="uk-margin">
                    <div class="uk-inline">
                        <span class="uk-form-icon" uk-icon="icon: user"></span>
                        <?= $this->formElement($form->get('pseudo')); ?>
                    </div>
                        <?=
                            $this->formElementErrors()
                            ->setMessageOpenFormat('<div class="uk-alert-danger uk-text-center" uk-alert><a class="uk-alert-close uk-text-right" uk-close></a><p>')
                            ->setMessageSeparatorString('</p></div><div class="uk-alert-danger uk-text-center" uk-alert><a class="uk-alert-close uk-text-right" uk-close></a><p>')
                            ->setMessageCloseString('</p></div>')
                            ->render($form->get('pseudo'));
                        ?>
                </div>
            	<div class="uk-margin">
                    <div class="uk-inline">
                        <span class="uk-form-icon" uk-icon="icon: lock"></span>
                        <?= $this->formElement($form->get('password')); ?>
                    </div>
                        <?=
                            $this->formElementErrors()
                            ->setMessageOpenFormat('<div class="uk-alert-danger uk-text-center" uk-alert><a class="uk-alert-close uk-text-right" uk-close></a><p>')
                            ->setMessageSeparatorString('</p></div><div class="uk-alert-danger uk-text-center" uk-alert><a class="uk-alert-close uk-text-right" uk-close></a><p>')
                            ->setMessageCloseString('</p></div>')
                            ->render($form->get('password'));
                        ?>
                </div>
            	<div class="uk-margin">
                    <div class="uk-inline">
                        <span class="uk-form-icon" uk-icon="icon: lock"></span>
                        <?= $this->formElement($form->get('confirm_password')); ?>
                    </div>
                        <?=
                            $this->formElementErrors()
                            ->setMessageOpenFormat('<div class="uk-alert-danger uk-text-center" uk-alert><a class="uk-alert-close uk-text-right" uk-close></a><p>')
                            ->setMessageSeparatorString('</p></div><div class="uk-alert-danger uk-text-center" uk-alert><a class="uk-alert-close uk-text-right" uk-close></a><p>')
                            ->setMessageCloseString('</p></div>')
                            ->render($form->get('confirm_password'));
                        ?>
                </div>
                <div class="uk-margin">
                    <div class="uk-inline">
                        <?= $this->formElement($form->get('select_role')); ?>
                        <?= $this->formElementErrors($form->get('select_role')); ?>
                    </div>
                </div>

                <?= $this->formElement($form->get('submit')); ?>
                <?= $this->form()->closeTag(); ?>

            	<div class="uk-align-center">
            		<div uk-form-custom="target: true"><input type="file"></div>
                </div>
            </fieldset>
        </form>
    </div>
</div>
