<div class="uk-child-width-1-3@s uk-grid-small uk-text-center" uk-grid>
    <div>
        <div class="uk-tile uk-tile-muted uk-padding-remove">
            <p class="uk-h4">Liste des utilisateurs</p>
        </div>
    </div>
<a class="uk-button uk-button-default" href="
    <?= $this->url('add.users'); ?>">
    <span></span> Nouveau utilisateur
</a>
<table class="uk-table uk-card uk-card-small uk-card-default uk-card-hover">

   <tr>
        <th>ID</th>
        <th>E-mail</th>
        <th>Full Name</th>
        <th>Date Created</th>
        <th>Actions</th>        
    </tr>
    
    <?php foreach ($users as $user): ?>
    
    <tr>
        <td><?= $this->escapeHtml($user->getId()); ?></td>
        <td>
            <a href="<?= $this->url('view.users', ['id'=>$user->getId()]); ?>">
                <?= $this->escapeHtml($user->getEmail()); ?>
            </a> 
        </td>
        <td><?= $this->escapeHtml($user->getFullName()); ?></a> 
        </td>
        <td><?= $this->escapeHtml($user->getDateCreated()); ?></td>
        <td>
        </td>    
    </tr>
        
    <?php endforeach; ?>   
    
</table>
</div>