<div class="uk-grid uk-grid-small uk-text-center" uk-grid>
    <div class="uk-width-2-3">
        <div class="uk-tile uk-tile-muted uk-padding-remove">
            <p class="uk-h4">Liste des utilisateurs</p>
        </div>
        <table class="uk-table uk-card uk-card-small uk-card-default uk-card-hover">
            <thead>
                <tr>
                    <th>ID</th>
                    <th>E-mail</th>
                    <th>Nom Prénom</th>
                    <th>Date de création</th>
                    <th>Rôle</th>
                </tr>
            </thead>

            <tbody>
                <?php foreach ($users as $user): ?>
                <tr>
                    <td><?= $this->escapeHtml($user->getId()); ?></td>
                    <td>
                        <a href="<?= $this->url('view.users', ['id'=>$user->getId()]); ?>">
                            <?= $this->escapeHtml($user->getEmail()); ?>
                        </a>
                    </td>
                    <td>
                        <?= $this->escapeHtml($user->getFullName()); ?>
                    </td>
                    <td><?= $this->escapeHtml($user->getDateCreated()); ?></td>
                    <td>
                        <?php
                            if($this->escapeHtml($user->getRole()) == 1 ) echo "Admin";
                            else if($this->escapeHtml($user->getRole()) == 2 ) echo "Auteur";
                            else echo "Abonné";
                        ?>
                    </td>
                </tr>
                <?php endforeach; ?>
            </tbody>
        </table>
    </div>

    <div class="uk-width-1-3">
        <a class="uk-button uk-button-default" href="<?= $this->url('add.users'); ?>">
            Nouveau utilisateur
        </a>
    </div>
</div>
