<div class="uk-align-center">
    <?php if (1 == $userAuth->getRole() && $user->getId() != $userAuth->getId()) : ?>
        <legend class="uk-legend">Compte de l'utilisateur <?= $this->escapeHtml($user->getFullName()) ?></legend>
    <?php else : ?>
        <legend class="uk-legend">Mon compte</legend>
    <?php endif; ?>
    <div class="uk-align-left uk-inline uk-card uk-card-small uk-card-default uk-card-hover">
        <table class="uk-table">
             <tr>
                <th>ID:</th>
                <td><?= $this->escapeHtml($user->getId()) ?></th>
            </tr>
            <tr>
                <th>E-mail:</th>
                <td><?= $this->escapeHtml($user->getEmail()) ?></th>
            </tr>
            <tr>
                <th>Pseudo:</th>
                <td><?= $this->escapeHtml($user->getPseudo()) ?></th>
            </tr>
            <tr>
                <th>Nom Prénom:</th>
                <td><?= $this->escapeHtml($user->getFullName()) ?></th>
            </tr>
            <tr>
                <th>Date de création:</th>
                <td><?= $this->escapeHtml($user->getDateCreated()) ?></th>
            </tr>
        </table>
		<div class="uk-align-right">
			<div uk-form-custom="target: true">
			<input type="file">
			</div>
			<a class="uk-button uk-button-default" href="<?= $this->url('list.users') ?>">Retour</a>
		</div>
    </div>
</div>
