<?php
$form->get('name')->setAttributes([
    'class'=>'uk-input',
    'placeholder'=>'Nom de la thématique'
    ]);

$form->get('submit')->setAttributes(['class'=>'uk-button']);

$form->prepare();
?>
<div class="uk-grid uk-grid-small" uk-grid>
    <div class="uk-width-3-3@m uk-text-center">
        <fieldset class="uk-fieldset">
            <legend class="uk-legend">Ajout d'une thématique</legend>
            <form method="post" class="uk-form-stacked">
                <?= $this->formElement($form->get('csrf')); ?>
                <div class="uk-margin">
                    <div class="uk-inline">
                        <span class="uk-form-icon" uk-icon="icon: user"></span>
                        <?= $this->formElement($form->get('name')); ?>
                    </div>
                    <?=
                    $this->formElementErrors()
                    ->setMessageOpenFormat('<div class="uk-alert-danger uk-text-center" uk-alert><a class="uk-alert-close uk-text-right" uk-close></a><p>')
                    ->setMessageSeparatorString('</p></div><div class="uk-alert-danger uk-text-center" uk-alert><a class="uk-alert-close uk-text-right" uk-close></a><p>')
                    ->setMessageCloseString('</p></div>')
                    ->render($form->get('name'));
                    ?>
                </div>
                <?= $this->formElement($form->get('submit')); ?>
                <a class="uk-button uk-button-default" href="<?= $this->url('list.themes'); ?>">Retour</a>
                <?= $this->form()->closeTag(); ?>
            </div>
        </form>
    </div>
</div>
