<?php<?php

$form->get('name')->setAttributes([
    'class'=>'uk-input',
    ]);

$form->get('submit')->setAttributes(['class'=>'uk-button']);

$form->prepare();
?>
<div class="uk-child-width-1-3@s uk-grid-small uk-text-center" uk-grid>
    <div>
        <div class="uk-tile uk-tile-muted uk-padding-remove">
            <p class="uk-h4">Modification de la thématique</p>
        </div>
    </div>
<form method="post" class="uk-form-stacked">
<?= $this->formElement($form->get('csrf')); ?>
	<div class="uk-align-center">
        <div class="uk-inline">
            <span class="uk-form-icon" uk-icon="icon: user"></span>
			<?= $this->formElement($form->get('name')); ?>
			<?= $this->formElementErrors($form->get('name')); ?>
        </div>
        <?= $this->formElement($form->get('submit')); ?>
    		<a class="uk-button uk-button-default" href="<?= $this->url('list.themes'); ?>">Retour</a>
        <?= $this->form()->closeTag(); ?>
    </div>
</form>
</div>
