<div class="uk-grid uk-grid-small uk-text-center" uk-grid>
    <div class="uk-width-2-3">
        <div class="uk-tile uk-tile-muted uk-padding-remove">
            <p class="uk-h4">Liste des thématiques</p>
        </div>
        </p>

        <table class="uk-table uk-card uk-card-small uk-card-default uk-card-hover">
            <thead>
                <tr>
                    <th class="uk-text-center">ID</th>
                    <th class="uk-text-center">Name</th>
                    <th class="uk-text-center">Action</th>
                </tr>
            </thead>

            <?php foreach ($themes as $theme): ?>
            <tbody>
                <tr>
                    <td><?= $this->escapeHtml($theme->getId()); ?></td>
                    <td>
                        <a href="<?= $this->url('view.themes', ['id'=>$theme->getId()]); ?>">
                            <?= $this->escapeHtml($theme->getName()); ?>
                        </a>
                    </td>
                    <td><a href="<?= $this->url('edit.themes', ['id'=>$theme->getId()]); ?>">
                            <?= $this->escapeHtml('Edit'); ?>
                    </a><a class="delete" data-confirm="Voulez-vous supprimer cet élément ?" href="<?= $this->url('delete.themes', ['id'=>$theme->getId()]); ?>">
                        <?= $this->escapeHtml('Delete'); ?>
                    </a></td>
                </tr>
            </tbody>
            <?php endforeach; ?>
        </table>
    </div>
    <div class="uk-width-1-3">
        <a class="uk-button uk-button-default" href="<?= $this->url('add.themes'); ?>">
             Nouvelle thématique
        </a>
    </div>
</div>
<script>
var deleteLinks = document.querySelectorAll('.delete');

for (var i = 0; i < deleteLinks.length; i++) {
  deleteLinks[i].addEventListener('click', function(event) {
      event.preventDefault();

      var choice = confirm(this.getAttribute('data-confirm'));

      if (choice) {
        window.location.href = this.getAttribute('href');
      }
  });
}
</script>