<div class="uk-child-width-1-3@s uk-grid-small uk-text-center" uk-grid>
    <div>
        <div class="uk-tile uk-tile-muted uk-padding-remove">
            <p class="uk-h4">Liste des thématiques</p>
        </div>
    </div>
<a class="uk-button" href="<?= $this->url('add.themes'); ?>">
     Nouvelle thématique
</a>
</p>

<table class="uk-table uk-card uk-card-small uk-card-default uk-card-hover">

   <tr>
        <th>ID</th>
        <th>Name</th>
        <th>Action</th>
    </tr>

    <?php foreach ($themes as $theme): ?>

    <tr>
        <td><?= $this->escapeHtml($theme->getId()); ?></td>
        <td>
            <a href="<?= $this->url('view.themes', ['id'=>$theme->getId()]); ?>">
                <?= $this->escapeHtml($theme->getName()); ?>
            </a>
        </td>
        <td><a href="<?= $this->url('edit.themes', ['id'=>$theme->getId()]); ?>">
                <?= $this->escapeHtml('Edit'); ?>
            </a></td>
    </tr>
    <?php endforeach; ?>
</table>
