<div class="uk-grid uk-grid-small uk-text-center" uk-grid>
    <div class="uk-width-2-3">
        <div class="uk-align-left">
            <table class="uk-table">
                <tbody>
                    <tr>
                        <th>ID:</th>
                        <td><?= $this->escapeHtml($theme->getId()) ?></td>
                    </tr>
                    <tr>
                        <th>Nom:</th>
                        <td><?= $this->escapeHtml($theme->getName()) ?></td>
                    </tr>
                </tbody>
            </table>
        </div>
        <div class="uk-margin">
			<a class="delete uk-button uk-button-danger" data-confirm="Voulez-vous supprimer cet élément ?" href="<?= $this->url('delete.themes', ['id'=>$theme->getId()]); ?>">
			    <?= $this->escapeHtml('Delete'); ?>
		    </a>
    	</div>
    	<div class="uk-margin">
            <a class="uk-button uk-button-default" href="<?= $this->url('list.themes'); ?>">
                Retour
            </a>
    	</div>
    </div>
</div>
<script>
var deleteLinks = document.querySelectorAll('.delete');

for (var i = 0; i < deleteLinks.length; i++) {
  deleteLinks[i].addEventListener('click', function(event) {
      event.preventDefault();

      var choice = confirm(this.getAttribute('data-confirm'));

      if (choice) {
        window.location.href = this.getAttribute('href');
      }
  });
}
</script>
